In [1]:
# Tugas Algoritma 5, Senin, 3 April 2023

# Latihan List 2 Dimensi 1 

# membuat matriks 3x3 dengan nilai awal 0
matriks = [[0 for j in range(3)] for i in range(3)]
print(matriks)

# membuat matriks 2x4 dengan nilai acak
import random
matriks = [[random.randint(0,9) for j in range(4)] for i in range(2)]
print(matriks)

# random.randint(a, b) adalah sebuah fungsi dalam modul random pada Python
# yang menghasilkan bilangan bulat acak di antara a dan b termasuk kedua batas tersebut. 
# Fungsi ini memerlukan dua parameter, yaitu a dan b, yang merupakan batas bawah dan batas 
# atas dari rentang bilangan bulat acak yang ingin dihasilkan.



[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0, 1, 6, 3], [6, 0, 3, 0]]


In [2]:
# Latihan List 2 Dimensi 2

matrik = [ [1,2,3,4],[2,4,6,8],[3,9,27,81],[1,3,5,7]]
print (matrik)

# Menempatkan sebuah list di dalam list dalam penempatan berbentuk matriks
# Jika dari contoh di atas, kita menulis fungsi untuk membuat list di matrik, dengan skalar yang sama, atau skalar yang
# random dengan fungsi random.randint (a,b). Jika di kode yang ini, kita menuliskan skalar secara langsung tanpa perlu 
# menuliskan kode untuk menampilkan skalar dari matrik tersebut.

[[1, 2, 3, 4], [2, 4, 6, 8], [3, 9, 27, 81], [1, 3, 5, 7]]


In [3]:
# Latihan List 2 Dimensi 3

# Mengakses elemen matrik
matrik [0]

# Mengakses elemen matrik di baris 0
# Bisa mengakses elemen matrik dengan menggunakan indeks. Indeks dimulai dari 0my_tuple = (1, 2, 3, 'a', 'b', 'c')


[1, 2, 3, 4]

In [4]:
# Latihan List 2 Dimensi 4

# Mengakses elemen matrik

matrik [3][0]

# Jika terdapat dua kurung siku seperti kode ini, maka kurung siku pertama mendeklarasikan baris dan kurung siku kedua
# mendeklarasikan kolom pada matriks
# Mengakses elemen di baris 3 dan kolom 0

1

In [5]:
# Latihan List 2 Dimensi 5

# Mengubah elemen matriks
matriks = [[1,2,3],[4,5,6],[7,8,9]]
matriks[0][0] = 10 # mengubah elemen di baris 0 dan kolom 0 menjadi 10
print(matriks)

# Menambahkan nilai di setiap elemen matriks
matriks = [[1,2,3],[4,5,6],[7,8,9]]
for i in range(len(matriks)):
    for j in range(len(matriks[i])):
        matriks[i][j] += 1
print(matriks)


[[10, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 3, 4], [5, 6, 7], [8, 9, 10]]


In [6]:
# Latihan list 2 Dimensi 6
for baris in matrik :
    print (baris)
    for kolom in baris :
        print (kolom)
        
# Kode ini berfungsi untuk memanggil list di matrik, dengan memanggil baris di matrik, dan memanggil kolom di bagian baris
print (" ")

for kolom in matrik :
    print (kolom) 
# Kode ini berfungsi untuk memanggil list di matrik, dengan memanggil kolom dalam matriknya.

[1, 2, 3, 4]
1
2
3
4
[2, 4, 6, 8]
2
4
6
8
[3, 9, 27, 81]
3
9
27
81
[1, 3, 5, 7]
1
3
5
7
 
[1, 2, 3, 4]
[2, 4, 6, 8]
[3, 9, 27, 81]
[1, 3, 5, 7]


In [7]:
# Latihan Tuples 1

# Membuat Tuple

# tuple kosong
my_tuple = ()
print (my_tuple)

# tuple dengan beberapa elemen
my_tuple = (1, 2, 3, 'a', 'b', 'c')
print (my_tuple)

# Tuple dapat dibuat dengan cara yang mirip dengan list, namun menggunakan tanda kurung () sebagai penanda. 
# Berikut adalah contoh pembuatan tuple kosong dan tuple dengan beberapa elemen

()
(1, 2, 3, 'a', 'b', 'c')


In [8]:
# Latihan Tuples 2

# Mengakses elemen tuple

print(my_tuple[0]) # output: 1
print(my_tuple[3]) # output: 'a'

# Mengakses elemen tuple dengan menggunakan indeks, seperti halnya pada list. 
# Indeks pada tuple dimulai dari 0. Berikut adalah contoh pengaksesan elemen tuple

1
a


In [9]:
# Latihan Tuples 3

# Tuple sebagai argumen fungsi

def hitung_rata(*angka):
    total = sum(angka)
    rata = total / len(angka)
    return rata

# contoh pemanggilan fungsi
rata = hitung_rata(1, 2, 3, 4, 5)
print(rata) # output: 3.0

# Pada contoh di atas, kita menggunakan *angka untuk menerima argumen yang bersifat tuple. 
# Dalam fungsi, kita bisa melakukan operasi pada elemen tuple seperti halnya pada list.


3.0


In [10]:
# Latihan Tuple 4

# Tuple Unpacking

my_tuple = (1, 2, 3)

# tuple unpacking
a, b, c = my_tuple

print(a) # output: 1
print(b) # output: 2
print(c) # output: 3

# Teknik untuk mengambil elemen tuple dan menyimpannya ke dalam beberapa variabel. 
# Misalnya, kita punya tuple dengan 3 elemen dan kita ingin menyimpannya ke dalam 3 variabel terpisah

1
2
3


In [11]:
# Latihan tuple 5

# Tuple sebagai return value fungsi

def hitung(a, b):
    tambah = a + b
    kurang = a - b
    kali = a * b
    bagi = a / b
    return tambah, kurang, kali, bagi

# contoh pemanggilan fungsi
hasil = hitung(10, 5)
print(hasil) # output: (15, 5, 50, 2.0)

# Pada contoh di atas, fungsi hitung mengembalikan tuple dengan 4 elemen. 
# Kita bisa menyimpan return value tersebut ke dalam sebuah variabel, atau menggunakan tuple unpacking 
# untuk menyimpannya ke dalam beberapa variabel terpisah


(15, 5, 50, 2.0)


In [12]:
# Latihan dictionaris 1

# Membuat dictionary

# dictionary kosong
my_dict = {}
print (my_dict)

# dictionary dengan beberapa pasangan key-value
my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}
print (my_dict)

# Dictionary dapat dibuat dengan menggunakan tanda kurung kurawal {} dan memasukkan pasangan key-value di dalamnya. 
# Di atas adalah contoh pembuatan dictionary kosong dan dictionary dengan beberapa pasangan key-value


{}
{'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}


In [13]:
# Latihan dictionaris 2

# Mengakses value pada dictionary

my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}

print(my_dict['nama']) # output: 'Andi'
print(my_dict['usia']) # output: 25

# Kita bisa mengakses value pada dictionary dengan menggunakan key-nya. 
# Di atas adalah contoh pengaksesan value pada dictionary


Andi
25


In [14]:
# Latihan dictionaris 3

# Menambahkan pasangan key-value pada dictionary

my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}
my_dict['pekerjaan'] = 'Programmer'
print(my_dict) # output: {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta', 'pekerjaan': 'Programmer'}

# Kita bisa menambahkan pasangan key-value baru pada dictionary dengan menggunakan sintaks dictionary[key] = value. 
# Di atas adalah contoh penambahan pasangan key-value pada dictionary

{'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta', 'pekerjaan': 'Programmer'}


In [15]:
# Latihan dictionaris 4

# Mengubah value pada dictionary

my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}
my_dict['usia'] = 26
print(my_dict) # output: {'nama': 'Andi', 'usia': 26, 'alamat': 'Jakarta'}

# Kita bisa mengubah value pada dictionary dengan cara yang sama seperti menambahkan pasangan key-value,
# yaitu dengan menggunakan sintaks dictionary[key] = value. 
# Di atas adalah contoh pengubahan value pada dictionary

{'nama': 'Andi', 'usia': 26, 'alamat': 'Jakarta'}


In [16]:
# Latihan dictionaris 5 

# Menghapus pasangan key-value pada dictionary

my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}
del my_dict['alamat']
print(my_dict) # output: {'nama': 'Andi', 'usia': 25}

# Kita bisa menghapus pasangan key-value pada dictionary dengan menggunakan sintaks del dictionary[key]. 
# Di atas adalah contoh penghapusan pasangan key-value pada dictionary

{'nama': 'Andi', 'usia': 25}


In [17]:
# Latihan dictionaris 6

# Looping pada dictionary

my_dict = {'nama': 'Andi', 'usia': 25, 'alamat': 'Jakarta'}
for key in my_dict:
    value = my_dict[key]
    print(key, value)

# output:
# nama Andi
# usia 25
# alamat Jakarta

# Kita bisa melakukan looping pada dictionary untuk mengakses semua pasangan key-value yang ada di dalamnya. 
# Di atas adalah contoh looping pada dictionary


nama Andi
usia 25
alamat Jakarta


In [18]:
# Latihan fungsi dalam python 1 

# Membuat fungsi

def tambah(angka1, angka2):
    hasil = angka1 + angka2
    return hasil
hasil = tambah (5,7)
print (hasil)

# Untuk membuat fungsi, kita menggunakan kata kunci def diikuti dengan nama fungsi, tanda kurung, dan titik dua. 
# Isi dari fungsi ditulis di dalam blok kode yang diberi indentasi. 
# Berikut adalah contoh pembuatan fungsi yang menerima dua argumen dan mengembalikan hasil penjumlahan kedua argumen

# Setelah fungsi dibuat, kita bisa memanggilnya di bagian lain dari program dengan menuliskan 
# nama fungsi diikuti dengan tanda kurung dan argumen yang diperlukan

12


In [19]:
# Latihan fungsi dalam python 2

# Fungsi tanpa argumen

def halo():
    print("Halo, selamat datang!")

halo() # output: Halo, selamat datang!

# Fungsi juga bisa dibuat tanpa argumen. Berikut adalah contoh pembuatan dan pemanggilan fungsi tanpa argumen

Halo, selamat datang!


In [20]:
# Latihann fungsi dalam python 3

# Fungsi dengan argumen default 

def sapa(nama=""):
    if nama == "":
        print("Halo, siapa namamu?")
    else:
        print("Halo, " + nama + "!")

sapa() # output: Halo, siapa namamu?
sapa("Indry") # output: Halo, Andi!

# Fungsi juga bisa memiliki argumen default. 
# Argumen default adalah nilai yang akan digunakan oleh fungsi jika argumen tersebut tidak diberikan saat pemanggilan fungsi.


Halo, siapa namamu?
Halo, Indry!


In [21]:
# Latihan fungsi dalam python 3

# Fungsi dengan jumlah argumen yang tidak diketahui

def jumlah(*angka):
    total = 0
    for a in angka:
        total += a
    return total

hasil = jumlah(1, 2, 3, 4, 5)
print(hasil) # output: 15

# Fungsi juga bisa menerima jumlah argumen yang tidak diketahui. 
# Untuk melakukan hal ini, kita menggunakan tanda asterisk (*) diikuti dengan nama variabel

15


In [22]:
# Latihan fungsi dalam python 4

def urutkan_matriks(matriks):
    #Fungsi ini menerima matriks berukuran n x n dan mengurutkan elemen-elemennya dari kecil ke besar#
    ukuran = len(matriks)
    for i in range(ukuran):
        for j in range(ukuran):
            for k in range(ukuran):
                for l in range(ukuran):
                    if matriks[i][j] < matriks[k][l]:
                        matriks[i][j], matriks[k][l] = matriks[k][l], matriks[i][j]
    return matriks

matriks = [[4, 2, 3],
           [1, 5, 6],
           [7, 8, 9]]

hasil = urutkan_matriks(matriks)
print(hasil)

# Fungsi ini menerima sebuah matriks berukuran n x n dan mengurutkan elemen-elemennya dari kecil ke besar. 
# Pengurutan dilakukan dengan membandingkan setiap pasangan elemen dalam matriks dan menukar posisi 
# elemen-elemen jika diperlukan.

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [23]:
# Latihan Numpy 1

# Perintah dasar dalam numpy

import numpy as np
# membuat array dengan list
a = np.array([1, 2, 3])
print(a) # output: [1 2 3]

# membuat array dengan tuple
b = np.array((4, 5, 6))
print(b) # output: [4 5 6]

# membuat array 2 dimensi
c = np.array([[1, 2], [3, 4]])
print(c) # output: [[1 2]
         #         [3 4]]

# Untuk membuat array numpy, kita bisa menggunakan fungsi array() dengan menyertakan list atau tuple sebagai argumen


[1 2 3]
[4 5 6]
[[1 2]
 [3 4]]


In [24]:
# Latihan Numpy 2

# Memanggil anggota, kolom, baris dengan numpy

import numpy as np
# membuat array 1 dimensi
a = np.array([1, 2, 3])
print (a)
print(a[0]) # output: 1
print(a[1]) # output: 2
print(a[2]) # output: 3

# membuat array 2 dimensi
b = np.array([[1, 2], [3, 4]])
print (b)
print(b[0, 0]) # output: 1
print(b[0, 1]) # output: 2
print(b[1, 0]) # output: 3
print(b[1, 1]) # output: 4

# membuat array 3 dimensi
c = np.array([[1,2,3],[2,5,6],[3,8,9]])
print (c)
print (c[1,2]) # output : 6
print (c[0,1]) # output : 2
print (c[2,2]) # output : 9
print (c[:,1]) # output : [2,5,8]

# Bisa menggunakan kode lain seperti ini
kolom_ketiga = c[:,2]
print (kolom_ketiga) # output : [3,6,9]

baris_ketiga = c[2,:]
print (baris_ketiga) # output : [3,8,9]

# untuk replace salah satu saklar dari matriks
b[0,0]=10
print (b) # output: [[10 2]
         #          [3 4]]


[1 2 3]
1
2
3
[[1 2]
 [3 4]]
1
2
3
4
[[1 2 3]
 [2 5 6]
 [3 8 9]]
6
2
9
[2 5 8]
[3 6 9]
[3 8 9]
[[10  2]
 [ 3  4]]


In [25]:
# Latihan numpy 3

# Membuat matriks dalam numpy

import numpy as np
# membuat matriks 2x3
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

# membuat matriks 3x3 dengan elemen 0
b = np.zeros((3, 3))
print(b)

# membuat matriks 3x3 dengan elemen 1
c = np.ones((3, 3))
print(c)

# membuat matriks identitas 3x3
d = np.eye(3)
print(d)

# membuat matriks acak 3x3 dengan nilai antara 0 dan 1
e = np.random.rand(3, 3)
print(e)

# membuat matriks acak 3x3 dengan nilai antara 3 dan 9
f = np.random.randint(3, 9, (3, 3))
print(f)

# membuat matrik ukuran 10x10 
g = np. random.randint(2,9,(10,10))
print (g)


[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.49690204 0.1929953  0.48758686]
 [0.16774474 0.68859208 0.12870287]
 [0.79979555 0.0664864  0.83710271]]
[[3 7 7]
 [6 7 4]
 [4 6 8]]
[[2 6 7 6 6 6 4 3 8 6]
 [7 6 8 7 6 3 5 2 7 7]
 [3 3 5 5 6 8 7 3 4 4]
 [4 4 6 7 5 5 5 6 8 2]
 [5 8 2 6 2 2 8 4 5 2]
 [3 5 2 8 7 8 4 8 7 7]
 [3 7 4 6 6 3 2 6 7 2]
 [7 5 5 5 7 8 4 5 4 6]
 [2 4 4 4 6 7 7 4 6 6]
 [2 3 4 2 6 4 8 2 3 6]]


In [26]:
# Latihan numpy 4

# Copy pada numpy

# membuat array 3 dimensi
c = np.array([[1, 2, 4], [3, 4, 7],[5, 8, 13]])
print(c) 

print (" ")
b=c
# akan mengeluarkan ouput yang sama dengan c, tetapi sudah dideklarasikan menjadi array b
print (b)

print (" ")
b[0,2]= 15
print (b)
# sehingga, saat melakukan suatu fungsi kepada array b, array a tidak akan terpengaruh

[[ 1  2  4]
 [ 3  4  7]
 [ 5  8 13]]
 
[[ 1  2  4]
 [ 3  4  7]
 [ 5  8 13]]
 
[[ 1  2 15]
 [ 3  4  7]
 [ 5  8 13]]


In [27]:
# Latihan numpy 5

# Operasi Matematika dalam Array

import numpy as np

# menghitung jumlah elemen pada array
a = np.array([1, 2, 3])
print(np.size(a)) # output: 3

# menghitung jumlah elemen pada array 2 dimensi
b = np.array([[1, 2], [3, 4]])
print(np.size(b)) # output: 4

# mengalikan array dengan skalar
c = np.array([1, 2, 3])
d = c * 2
print(d) # output: [2 4 6]

# menjumlahkan dua array
e = np.array([1, 2, 3])
f = np.array([4, 5, 6])
g = e + f
print(g) # output: [5 7 9]

# mengalikan dua array
h = np.array([1, 2, 3])
i = np.array([4, 5, 6])
j = h * i
print(j) # output: [ 4 10 18]


3
4
[2 4 6]
[5 7 9]
[ 4 10 18]


In [28]:
# Latihan numpy 6

# Perkalian matrik pada numpy

import numpy as np

# contoh matriks A
A = np.array([[1, 2, 3], [4, 5, 6]])

# contoh matriks B
B = np.array([[7, 8, 6], [9, 10, 14], [11, 12, 15]])

# perkalian matriks menggunakan dot()
C = np.dot(A, B)
print(C)

# perkalian matriks menggunakan operator @
D = A @ B
print(D)

# perkalian elemen-wise menggunakan operator *
E = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
F = np.array([[7, 8, 6], [9, 10, 14], [11, 12, 15]])
G = E * F
print(G)

# Untuk melakukan perkalian matriks pada NumPy, kita dapat menggunakan fungsi dot() atau operator @.
# Namun, untuk melakukan perkalian elemen-wise (perkalian satu-satu), kita dapat menggunakan operator *.

# Pada contoh di atas, kita membuat dua matriks A dan B, lalu melakukan perkalian matriks dengan 
# menggunakan fungsi dot() atau operator @. Hasilnya disimpan pada matriks C dan D. 
# Selain itu, kita juga melakukan perkalian elemen-wise menggunakan operator *, dan hasilnya disimpan pada matriks E.

[[ 58  64  79]
 [139 154 184]]
[[ 58  64  79]
 [139 154 184]]
[[  7  16  18]
 [ 36  50  84]
 [ 77  96 135]]


In [29]:
# Latihan numpy 7

# min, max, dan sum pada numpy
# NumPy memiliki fungsi built-in yang memungkinkan kita untuk melakukan operasi min, max, dan sum pada array. 
# Fungsi-fungsi tersebut adalah:

# np.min(arr): mengembalikan nilai minimum dari seluruh elemen array arr.
# np.max(arr): mengembalikan nilai maksimum dari seluruh elemen array arr.
# np.sum(arr): mengembalikan jumlah dari seluruh elemen array arr.
# Kita juga dapat menentukan sum atau minimum/maximum untuk suatu sumbu tertentu dengan menambahkan parameter axis. Contohnya:

# np.min(arr, axis=0): mengembalikan nilai minimum untuk setiap kolom array arr.
# np.max(arr, axis=1): mengembalikan nilai maksimum untuk setiap baris array arr.
# np.sum(arr, axis=0): mengembalikan jumlah untuk setiap kolom array arr.
# np.sum(arr, axis=1): mengembalikan jumlah untuk setiap baris array arr.

import numpy as np
# contoh array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# nilai minimum
min_val = np.min(arr)
print("Nilai minimum:", min_val)

# nilai maksimum
max_val = np.max(arr)
print("Nilai maksimum:", max_val)

# jumlah elemen
sum_val = np.sum(arr)
print("Jumlah elemen:", sum_val)

# nilai minimum untuk setiap kolom
min_col = np.min(arr, axis=0)
print("Nilai minimum untuk setiap kolom:", min_col)

# nilai maksimum untuk setiap baris
max_row = np.max(arr, axis=1)
print("Nilai maksimum untuk setiap baris:", max_row)

# jumlah untuk setiap kolom
sum_col = np.sum(arr, axis=0)
print("Jumlah untuk setiap kolom:", sum_col)

# jumlah untuk setiap baris
sum_row = np.sum(arr,axis=1)
print ("Jumlah untuk setiap baris : ", sum_row)

# Pada contoh di atas, kita membuat array arr dengan dimensi 3x3, 
# lalu melakukan operasi min, max, dan sum menggunakan fungsi np.min(), np.max(), dan np.sum(). 
# Selain itu, kita juga melakukan operasi min dan max untuk setiap kolom dan baris menggunakan parameter axis


Nilai minimum: 1
Nilai maksimum: 9
Jumlah elemen: 45
Nilai minimum untuk setiap kolom: [1 2 3]
Nilai maksimum untuk setiap baris: [3 6 9]
Jumlah untuk setiap kolom: [12 15 18]
Jumlah untuk setiap baris :  [ 6 15 24]
